try to run twice

diff --git a/.github/workflows/cachix-populate.yaml b/.github/workflows/cachix-populate.yaml
--- a/.github/workflows/cachix-populate.yaml
+++ b/.github/workflows/cachix-populate.yaml
@@ -26,35 +26,44 @@ jobs:
         run: |
           nix profile install --accept-flake-config \
             github:cachix/devenv/v${{ matrix.devenv-ver }}
-      - name: Run devenv shell (fails)
+      - name: Run devenv shell (output1.log, fails)
+        conntinue-on-error: true
         run: |
           set -x
           log=output.log
           devenv shell -- true 2>&1 | tee $log
-          ls -al $log
-          search=(
-            "Binary cache enfoldsystems doesn"
-            "does not appear to be a binary cache"
-          )
-          for string in "${search[@]}"; do
-            if grep -q "$string" "$log"; then
-              echo "Error: "$search" found in "$log""
-              exit 1
-            fi
-          done
-      - name: Run devenv shell again (works)
+      - name: Run devenv shell again (output2.log works)
         run: |
           set -x
           log=output2.log
           devenv shell -- true 2>&1 | tee $log
-          ls -al $log
-          search=(
-            "Binary cache enfoldsystems doesn"
-            "does not appear to be a binary cache"
-          )
-          for string in "${search[@]}"; do
-            if grep -q "$string" "$log"; then
-              echo "Error: "$search" found in "$log""
-              exit 1
-            fi
-          done
+      -name: check output2.log for failure
+       run: |
+         log=output2.log
+         ls -al $log
+         search=(
+           "Binary cache enfoldsystems doesn"
+           "does not appear to be a binary cache"
+         )
+         for string in "${search[@]}"; do
+           if grep -q "$string" "$log"; then
+             echo "Error: "$search" found in "$log""
+             exit 1
+           fi
+         done
+      -name: check output.log for failure
+       run: |
+         log=output2.log
+         ls -al $log
+         search=(
+           "Binary cache enfoldsystems doesn"
+           "does not appear to be a binary cache"
+         )
+         for string in "${search[@]}"; do
+           if grep -q "$string" "$log"; then
+             echo "Error: "$search" found in "$log""
+             exit 1
+           fi
+         done
+
+      
