madness takes many forms

diff --git a/.github/workflows/cachix-populate.yaml b/.github/workflows/cachix-populate.yaml
--- a/.github/workflows/cachix-populate.yaml
+++ b/.github/workflows/cachix-populate.yaml
@@ -27,9 +27,15 @@ jobs:
       - name: Run devenv shell
         run: |
           log=output.log
-          search="Binary cache enfoldsystems doesn\'t exist"
-          devenv shell -- true 2>&1 | tee $log
-          if grep -q  "$log"; then
-            echo "Error: "$search" found in "$log""
-            exit 1
-          fi
+          devenv -v shell -- true 2>&1 | tee $log
+          ls -al output.log
+          search=(
+            "Binary cache enfoldsystems doesn\'t exist"
+            "https://enfoldsystems.cachix.org does not appear to be a"
+          )
+          for string in "${search[@]}"; do
+            if grep -q  "$log"; then
+              echo "Error: "$search" found in "$log""
+              exit 1
+            fi
+          done
